name: "Build, Test and Lint"

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      concurrency-group:
        required: false
        type: string
      node-version:
        required: false
        type: string
        description: 'Node.js version to use'
        default: '18'

concurrency:
  group: ${{ inputs.concurrency-group || github.head_ref }}
  cancel-in-progress: true

jobs:
  install:
    name: "Install deps"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: vtno/seaeye/.github/actions/yarn-install@v0.1.0
        with:
          working-dir: ${{ inputs.working-dir }}
          node-version: ${{ inputs.node-version }}

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    steps:
      - uses: vtno/seaeye/.github/actions/yarn-build@v0.1.0
        with:
          working-dir: ${{ inputs.working-dir }}
          node-version: ${{ inputs.node-version }}

  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    steps:
      - uses: vtno/seaeye/.github/actions/yarn-test@v0.1.0
        with:
          working-dir: ${{ inputs.working-dir }}
          node-version: ${{ inputs.node-version }}

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    steps:
      - uses: vtno/seaeye/.github/actions/yarn-lint@v0.1.0
        with:
          working-dir: ${{ inputs.working-dir }}
          node-version: ${{ inputs.node-version }}
