name: Testing Build & Release
on: 
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
jobs:
  call-build-workflow:
    uses: npcopter/seaeye/.github/workflows/build.yml@add-setup-node
    with:
      working-dir: example