name: Testing Build & Release
on: 
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
jobs:
  call-build-workflow:
    uses: npcopter/seaeye/.github/workflows/build.yml@refactor-node-version
    with:
      working-dir: example
      node-version: '18'
      concurrency-group: 'test'
