name: Testing Build & Release
on: 
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
jobs:
  call-build-workflow:
    uses: npcopter/seaeye/.github/workflows/build.yml@ea4e641298b558505600c3c90f1617a8d9f7f4bb
    with:
      working-dir: example